services:
  db:
    image: postgres:16
    container_name: main_db
    env_file:
      - subscriptions/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - api_network

  api:
    container_name: main_api
    build:
      context: subscriptions
      dockerfile: dockerfile
    env_file:
      - subscriptions/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_network
    ports:
      - "8080:8080"

networks:
  api_network:
    driver: bridge